FROM quay.io/pypa/manylinux_2_24_x86_64

ENV OPENSSL=openssl-3.4.0
ENV LIBSSH=0.11.1
ENV SYSTEM_LIBSSH=1
ENV KRB=1.21.3
ENV CFLAGS="-g0 -s"

RUN apt-get update -y && apt-get install zlib1g-dev cmake -y

ADD libssh-${LIBSSH}.tar.gz libssh.tar.gz
ADD krb5-${KRB}.tar.gz krb5.tar.gz
ADD https://www.openssl.org/source/${OPENSSL}.tar.gz ${OPENSSL}.tar.gz


# Kerberos
RUN cd krb5.tar.gz/krb5-${KRB}/src && \
    ./configure && \
    make -j6 && \
    make install


RUN tar -xzf ${OPENSSL}.tar.gz
# Openssl
RUN cd ${OPENSSL} && \
    ./config --prefix=/usr --openssldir=/usr/openssl threads shared && \
    make -j6 && make install_sw


# Libssh
RUN cc --version; openssl version -a; mkdir -p build_libssh && cd build_libssh && \
    cmake3 ../libssh.tar.gz/libssh -DCMAKE_BUILD_TYPE=Release \
          -DWITH_GSSAPI=ON -DWITH_EXAMPLES=OFF -DUNIT_TESTING=OFF && \
    make -j6 install/strip

RUN rm -rf ${OPENSSL}* libssh.tar.gz build_libssh krb5.tar.gz

VOLUME /var/cache
